title: "Svastikkka's Blog"
description: "Exploring and simplifying machine learning concepts"
author: Manshu Sharma
url: "https://svastikkka.github.io"
url: "https://svastikkka.github.io/SVASTIKKKA"
base: '/'

theme: minima
markdown: kramdown
